#!/bin/bash
set -euxo pipefail
Date=`date +"%m-%d-%Y"`

cd /home/liuhui/trace_rss
python3 rss2table.py table >>content.db
sort -k1,1 -k2,2nr content.db |uniq >content.db.sortuq
mv content.db.sortuq content.db

grep 'genom\|assembly\|sequencing' content.db >content.db.genome

cat head.html >index.html
touch prev.html prev-all.html
echo "<h3>Updated in ${Date}</h3>" >>index.html
cat prev.html >>index.html

cp index.html index-all.html
cut -f3 content.db.genome >>index.html
cut -f3 content.db >>index-all.html

cat prev.html foot.html >>index.html
cat prev-all.html foot.html >>index-all.html


#debug
#cp index.html ../themes/casper/test.html

#production
cat index.html >/home/liuhui/themes/casper/rss.html
cat index-all.html >/home/liuhui/themes/casper/rss-all.html
