#!/bin/bash
set -euo pipefail

# ARG_OPTIONAL_SINGLE([output],[o],[output directory],[./])
# ARG_OPTIONAL_SINGLE([keyword],[k],[specify keyword],[genom\|assembly\|sequencing])
# ARG_OPTIONAL_BOOLEAN([rotate],[],[archive current html and clear database],[off])
# ARG_POSITIONAL_SINGLE([rss_table],[The rss_table file],[table])
# ARG_HELP([Table2HTML: transform rss feeds into html file])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.8.1 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.io for more info
# Generated online by https://argbash.io/generate


die()
{
    local _ret=$2
    test -n "$_ret" || _ret=1
    test "$_PRINT_HELP" = yes && print_help >&2
    echo "$1" >&2
    exit ${_ret}
}


begins_with_short_option()
{
    local first_option all_short_options='okh'
    first_option="${1:0:1}"
    test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - POSITIONALS
_positionals=()
_arg_rss_table="table"
# THE DEFAULTS INITIALIZATION - OPTIONALS
_arg_output="./"
_arg_keyword="genom\|assembly\|sequencing"
_arg_rotate="off"


print_help()
{
    printf '%s\n' "Table2HTML: transform rss feeds into html file"
    printf 'Usage: %s [-o|--output <arg>] [-k|--keyword <arg>] [--(no-)rotate] [-h|--help] [<rss_table>]\n' "$0"
    printf '\t%s\n' "<rss_table>: The rss_table file (default: 'table')"
    printf '\t%s\n' "-o, --output: output directory (default: './')"
    printf '\t%s\n' "-k, --keyword: specify keyword (default: 'genom\|assembly\|sequencing')"
    printf '\t%s\n' "--rotate, --no-rotate: archive current html and clear database (off by default)"
    printf '\t%s\n' "-h, --help: Prints help"
}


parse_commandline()
{
    _positionals_count=0
    while test $# -gt 0
    do
        _key="$1"
        case "$_key" in
            -o|--output)
                test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
                _arg_output="$2"
                shift
                ;;
            --output=*)
                _arg_output="${_key##--output=}"
                ;;
            -o*)
                _arg_output="${_key##-o}"
                ;;
            -k|--keyword)
                test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
                _arg_keyword="$2"
                shift
                ;;
            --keyword=*)
                _arg_keyword="${_key##--keyword=}"
                ;;
            -k*)
                _arg_keyword="${_key##-k}"
                ;;
            --no-rotate|--rotate)
                _arg_rotate="on"
                test "${1:0:5}" = "--no-" && _arg_rotate="off"
                ;;
            -h|--help)
                print_help
                exit 0
                ;;
            -h*)
                print_help
                exit 0
                ;;
            *)
                _last_positional="$1"
                _positionals+=("$_last_positional")
                _positionals_count=$((_positionals_count + 1))
                ;;
        esac
        shift
    done
}


handle_passed_args_count()
{
    test "${_positionals_count}" -le 1 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect between 0 and 1, but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
}


assign_positional_args()
{
    local _positional_name _shift_for=$1
    _positional_names="_arg_rss_table "

    shift "$_shift_for"
    for _positional_name in ${_positional_names}
    do
        test $# -gt 0 || break
        eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
        shift
    done
}

parse_commandline "$@"
handle_passed_args_count
if [ ! -z ${_positionals+x} ]
then
    assign_positional_args 1 "${_positionals[@]}"
fi

# OTHER STUFF GENERATED BY Argbash

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash


#echo "Value of --ooutput: $_arg_output"
#echo "rotate is $_arg_rotate"
#echo "keyword is $_arg_keyword"
#echo "Value of positional-arg: $_arg_rss_table"

# ] <-- needed because of Argbash

